export const locales = ["en", "tr", "de", "es", "fr", "it", "pt", "nl", "ar", "ja", "ko", "zh"] as const;
export type Locale = (typeof locales)[number];

export const localeNames: Record<Locale, string> = {
  en: "English", tr: "Türkçe", de: "Deutsch", es: "Español", fr: "Français", it: "Italiano",
  pt: "Português", nl: "Nederlands", ar: "العربية", ja: "日本語", ko: "한국어", zh: "中文",
};

const english = {
  appName: "Pratix Bridge", heroTitle: "Move what matters. Directly.", heroBody: "A private bridge for text and files between your devices—without a shared Wi‑Fi network.",
  create: "Create", join: "Join", createBridge: "Create a bridge", enterPin: "Enter the 6-digit PIN", sharePin: "Share this PIN", scanQr: "or scan the QR code",
  connecting: "Connecting", waiting: "Waiting for a device", connected: "Securely connected", restart: "Restart", text: "Text", messagePlaceholder: "Write a message…",
  send: "Send", files: "Files", selectFiles: "Select files", queue: "Transfer queue", download: "Download", noFiles: "No file transfers yet", status: "Connection status",
  security: "End-to-end encrypted peer connection", expires: "Pairing expires in 10 minutes", ad: "Advertisement", article: "How direct P2P transfer works",
};
type BaseTranslationKey = keyof typeof english;

export const dictionaries: Record<Locale, Record<BaseTranslationKey, string>> = {
  en: english,
  tr: { appName: "Pratix Köprü", heroTitle: "Önemli olanı doğrudan taşıyın.", heroBody: "Aynı Wi‑Fi ağı gerekmeden cihazlarınız arasında metin ve dosyalar için özel köprü.", create: "Oluştur", join: "Katıl", createBridge: "Köprü oluştur", enterPin: "6 haneli PIN'i girin", sharePin: "Bu PIN'i paylaşın", scanQr: "veya QR kodu tarayın", connecting: "Bağlanıyor", waiting: "Cihaz bekleniyor", connected: "Güvenle bağlandı", restart: "Yeniden başlat", text: "Metin", messagePlaceholder: "Mesaj yazın…", send: "Gönder", files: "Dosyalar", selectFiles: "Dosya seç", queue: "Aktarım kuyruğu", download: "İndir", noFiles: "Henüz dosya aktarımı yok", status: "Bağlantı durumu", security: "Uçtan uca şifreli eş bağlantı", expires: "Eşleştirme 10 dakika içinde sona erer", ad: "Reklam", article: "Doğrudan P2P aktarımı nasıl çalışır" },
  de: { appName: "Pratix Bridge", heroTitle: "Direkt übertragen, was zählt.", heroBody: "Eine private Brücke für Texte und Dateien zwischen Ihren Geräten—ohne gemeinsames WLAN.", create: "Erstellen", join: "Beitreten", createBridge: "Brücke erstellen", enterPin: "6-stellige PIN eingeben", sharePin: "Diesen PIN teilen", scanQr: "oder QR-Code scannen", connecting: "Verbindung wird hergestellt", waiting: "Warte auf ein Gerät", connected: "Sicher verbunden", restart: "Neu starten", text: "Text", messagePlaceholder: "Nachricht schreiben…", send: "Senden", files: "Dateien", selectFiles: "Dateien auswählen", queue: "Übertragungswarteschlange", download: "Herunterladen", noFiles: "Noch keine Dateiübertragungen", status: "Verbindungsstatus", security: "Ende-zu-Ende-verschlüsselte Peer-Verbindung", expires: "Kopplung läuft in 10 Minuten ab", ad: "Werbung", article: "So funktioniert direkter P2P-Transfer" },
  es: { appName: "Pratix Bridge", heroTitle: "Mueve lo importante. Directamente.", heroBody: "Un puente privado para textos y archivos entre tus dispositivos, sin compartir una red Wi‑Fi.", create: "Crear", join: "Unirse", createBridge: "Crear un puente", enterPin: "Introduce el PIN de 6 dígitos", sharePin: "Comparte este PIN", scanQr: "o escanea el código QR", connecting: "Conectando", waiting: "Esperando un dispositivo", connected: "Conexión segura", restart: "Reiniciar", text: "Texto", messagePlaceholder: "Escribe un mensaje…", send: "Enviar", files: "Archivos", selectFiles: "Seleccionar archivos", queue: "Cola de transferencia", download: "Descargar", noFiles: "Aún no hay transferencias", status: "Estado de conexión", security: "Conexión peer cifrada de extremo a extremo", expires: "El emparejamiento vence en 10 minutos", ad: "Publicidad", article: "Cómo funciona la transferencia P2P directa" },
  fr: { appName: "Pratix Bridge", heroTitle: "Transférez l'essentiel. Directement.", heroBody: "Un pont privé pour les textes et fichiers entre vos appareils, sans réseau Wi‑Fi commun.", create: "Créer", join: "Rejoindre", createBridge: "Créer un pont", enterPin: "Saisissez le PIN à 6 chiffres", sharePin: "Partagez ce PIN", scanQr: "ou scannez le code QR", connecting: "Connexion en cours", waiting: "En attente d'un appareil", connected: "Connexion sécurisée", restart: "Redémarrer", text: "Texte", messagePlaceholder: "Écrivez un message…", send: "Envoyer", files: "Fichiers", selectFiles: "Sélectionner des fichiers", queue: "File de transfert", download: "Télécharger", noFiles: "Aucun transfert pour le moment", status: "État de la connexion", security: "Connexion pair à pair chiffrée de bout en bout", expires: "L'appairage expire dans 10 minutes", ad: "Publicité", article: "Comment fonctionne le transfert P2P direct" },
  it: { appName: "Pratix Bridge", heroTitle: "Sposta ciò che conta. Direttamente.", heroBody: "Un ponte privato per testi e file tra i tuoi dispositivi, senza Wi‑Fi condiviso.", create: "Crea", join: "Unisciti", createBridge: "Crea un ponte", enterPin: "Inserisci il PIN di 6 cifre", sharePin: "Condividi questo PIN", scanQr: "oppure scansiona il QR code", connecting: "Connessione in corso", waiting: "In attesa di un dispositivo", connected: "Connesso in modo sicuro", restart: "Riavvia", text: "Testo", messagePlaceholder: "Scrivi un messaggio…", send: "Invia", files: "File", selectFiles: "Seleziona file", queue: "Coda di trasferimento", download: "Scarica", noFiles: "Nessun trasferimento per ora", status: "Stato della connessione", security: "Connessione peer crittografata end-to-end", expires: "L'abbinamento scade tra 10 minuti", ad: "Pubblicità", article: "Come funziona il trasferimento P2P diretto" },
  pt: { appName: "Pratix Bridge", heroTitle: "Mova o que importa. Diretamente.", heroBody: "Uma ponte privada para textos e ficheiros entre os seus dispositivos, sem Wi‑Fi partilhado.", create: "Criar", join: "Entrar", createBridge: "Criar uma ponte", enterPin: "Introduza o PIN de 6 dígitos", sharePin: "Partilhe este PIN", scanQr: "ou leia o código QR", connecting: "A ligar", waiting: "À espera de um dispositivo", connected: "Ligação segura", restart: "Reiniciar", text: "Texto", messagePlaceholder: "Escreva uma mensagem…", send: "Enviar", files: "Ficheiros", selectFiles: "Selecionar ficheiros", queue: "Fila de transferência", download: "Transferir", noFiles: "Ainda não há transferências", status: "Estado da ligação", security: "Ligação peer encriptada de ponta a ponta", expires: "O emparelhamento expira em 10 minutos", ad: "Publicidade", article: "Como funciona a transferência P2P direta" },
  nl: { appName: "Pratix Bridge", heroTitle: "Verplaats wat telt. Rechtstreeks.", heroBody: "Een privébrug voor tekst en bestanden tussen uw apparaten, zonder gedeelde wifi.", create: "Maken", join: "Deelnemen", createBridge: "Brug maken", enterPin: "Voer de 6-cijferige PIN in", sharePin: "Deel deze PIN", scanQr: "of scan de QR-code", connecting: "Verbinden", waiting: "Wachten op een apparaat", connected: "Veilig verbonden", restart: "Opnieuw starten", text: "Tekst", messagePlaceholder: "Schrijf een bericht…", send: "Verzenden", files: "Bestanden", selectFiles: "Bestanden kiezen", queue: "Overdrachtswachtrij", download: "Downloaden", noFiles: "Nog geen bestandsoverdrachten", status: "Verbindingsstatus", security: "End-to-end versleutelde peerverbinding", expires: "Koppeling verloopt over 10 minuten", ad: "Advertentie", article: "Hoe directe P2P-overdracht werkt" },
  ar: { appName: "جسر براتيكس", heroTitle: "انقل ما يهم. مباشرة.", heroBody: "جسر خاص للنصوص والملفات بين أجهزتك دون شبكة واي فاي مشتركة.", create: "إنشاء", join: "انضمام", createBridge: "إنشاء جسر", enterPin: "أدخل رمز PIN المكون من 6 أرقام", sharePin: "شارك رمز PIN هذا", scanQr: "أو امسح رمز QR", connecting: "جارٍ الاتصال", waiting: "بانتظار جهاز", connected: "متصل بأمان", restart: "إعادة البدء", text: "نص", messagePlaceholder: "اكتب رسالة…", send: "إرسال", files: "ملفات", selectFiles: "اختر ملفات", queue: "قائمة النقل", download: "تنزيل", noFiles: "لا توجد عمليات نقل بعد", status: "حالة الاتصال", security: "اتصال نظير مشفر من طرف إلى طرف", expires: "تنتهي صلاحية الاقتران خلال 10 دقائق", ad: "إعلان", article: "كيف يعمل النقل المباشر P2P" },
  ja: { appName: "Pratix Bridge", heroTitle: "大切なものを、直接届ける。", heroBody: "同じWi‑Fiを使わずに、端末間でテキストとファイルを送るプライベートブリッジです。", create: "作成", join: "参加", createBridge: "ブリッジを作成", enterPin: "6桁のPINを入力", sharePin: "このPINを共有", scanQr: "またはQRコードをスキャン", connecting: "接続中", waiting: "端末を待機中", connected: "安全に接続済み", restart: "再開", text: "テキスト", messagePlaceholder: "メッセージを書く…", send: "送信", files: "ファイル", selectFiles: "ファイルを選択", queue: "転送キュー", download: "ダウンロード", noFiles: "まだ転送はありません", status: "接続状態", security: "エンドツーエンド暗号化されたピア接続", expires: "ペアリングは10分で期限切れになります", ad: "広告", article: "直接P2P転送の仕組み" },
  ko: { appName: "Pratix Bridge", heroTitle: "중요한 것을 직접 옮기세요.", heroBody: "같은 Wi‑Fi 없이 기기 사이에서 텍스트와 파일을 전송하는 개인 브리지입니다.", create: "만들기", join: "참가", createBridge: "브리지 만들기", enterPin: "6자리 PIN 입력", sharePin: "이 PIN 공유", scanQr: "또는 QR 코드 스캔", connecting: "연결 중", waiting: "기기 대기 중", connected: "안전하게 연결됨", restart: "다시 시작", text: "텍스트", messagePlaceholder: "메시지 작성…", send: "보내기", files: "파일", selectFiles: "파일 선택", queue: "전송 대기열", download: "다운로드", noFiles: "아직 파일 전송이 없습니다", status: "연결 상태", security: "종단간 암호화된 피어 연결", expires: "페어링은 10분 후 만료됩니다", ad: "광고", article: "직접 P2P 전송 작동 방식" },
  zh: { appName: "Pratix Bridge", heroTitle: "直接传递重要内容。", heroBody: "无需共享 Wi‑Fi，即可在设备之间私密传输文本和文件。", create: "创建", join: "加入", createBridge: "创建桥接", enterPin: "输入 6 位 PIN", sharePin: "分享此 PIN", scanQr: "或扫描二维码", connecting: "正在连接", waiting: "正在等待设备", connected: "已安全连接", restart: "重新开始", text: "文本", messagePlaceholder: "写一条消息…", send: "发送", files: "文件", selectFiles: "选择文件", queue: "传输队列", download: "下载", noFiles: "暂无文件传输", status: "连接状态", security: "端到端加密的点对点连接", expires: "配对将在 10 分钟后过期", ad: "广告", article: "直接 P2P 传输如何工作" },
};

const additionalDictionaries = {
  en: { browserToBrowser: "Browser-to-browser transfer", ready: "Ready to pair", pairingExpired: "Pairing expired", needsAttention: "Needs attention", createDescription: "Generate a time-limited code, then let the other device join with the PIN or QR code.", copy: "Copy", copied: "Copied", feedback: "Transfer feedback", directMessages: "Your direct messages will appear here.", item: "item", items: "items", sending: "Sending", receiving: "Receiving", noStorage: "No file storage", pairingWindow: "10-minute pairing window", worksAcrossNetworks: "Works across networks", handoffTitle: "Built for a clean handoff.", handoffBody: "A PIN is only for pairing. Your selected text and files travel directly between the two connected browsers.", adTitle: "Reserved, non-interruptive placement", adBody: "Sponsored content can appear here without covering transfer controls or task feedback.", privacy: "Privacy by design", privacyBody: "Keep the page open while a transfer is active. Close the bridge when you are finished to remove the pairing metadata.", installTitle: "Add Pratix Bridge to your home screen.", installHint: "On iPhone or iPad, open this page in Safari, tap Share, then choose Add to Home Screen. On supported Android and Chromium browsers, use the browser install option if a prompt does not appear here." },
  tr: { browserToBrowser: "Tarayıcıdan tarayıcıya aktarım", ready: "Eşleşmeye hazır", pairingExpired: "Eşleştirme süresi doldu", needsAttention: "İşlem gerekiyor", createDescription: "Süreli bir kod oluşturun; diğer cihaz PIN veya QR kodu ile katılsın.", copy: "Kopyala", copied: "Kopyalandı", feedback: "Aktarım geri bildirimi", directMessages: "Doğrudan mesajlarınız burada görünecek.", item: "öğe", items: "öğe", sending: "Gönderiliyor", receiving: "Alınıyor", noStorage: "Dosya depolama yok", pairingWindow: "10 dakikalık eşleştirme penceresi", worksAcrossNetworks: "Ağlar arasında çalışır", handoffTitle: "Temiz bir aktarım için tasarlandı.", handoffBody: "PIN yalnızca eşleştirme içindir. Seçtiğiniz metin ve dosyalar iki tarayıcı arasında doğrudan gider.", adTitle: "Ayrılmış, kesintisiz alan", adBody: "Sponsorlu içerik burada aktarım denetimlerini veya görev geri bildirimini örtmeden görünebilir.", privacy: "Tasarımdan gelen gizlilik", privacyBody: "Aktarım sürerken sayfayı açık tutun. İşiniz bitince eşleştirme verisini kaldırmak için köprüyü kapatın.", installTitle: "Pratix Köprü'yü ana ekranınıza ekleyin.", installHint: "iPhone veya iPad'de sayfayı Safari ile açın, Paylaş'a dokunun ve Ana Ekrana Ekle'yi seçin. Desteklenen Android ve Chromium tarayıcılarında istem görünmezse tarayıcının yükleme seçeneğini kullanın." },
  de: { browserToBrowser: "Browser-zu-Browser-Transfer", ready: "Bereit zum Koppeln", pairingExpired: "Kopplung abgelaufen", needsAttention: "Aktion erforderlich", createDescription: "Erstellen Sie einen zeitlich begrenzten Code, dann tritt das andere Gerät per PIN oder QR-Code bei.", copy: "Kopieren", copied: "Kopiert", feedback: "Übertragungsstatus", directMessages: "Ihre direkten Nachrichten erscheinen hier.", item: "Element", items: "Elemente", sending: "Wird gesendet", receiving: "Wird empfangen", noStorage: "Keine Dateispeicherung", pairingWindow: "10 Minuten Kopplungszeit", worksAcrossNetworks: "Netzwerkübergreifend", handoffTitle: "Für eine klare Übergabe gebaut.", handoffBody: "Die PIN dient nur der Kopplung. Ihre Texte und Dateien gehen direkt zwischen beiden Browsern.", adTitle: "Reservierter, nicht störender Bereich", adBody: "Gesponserte Inhalte können hier erscheinen, ohne Transfersteuerung oder Rückmeldungen zu verdecken.", privacy: "Datenschutz durch Design", privacyBody: "Lassen Sie die Seite während des Transfers geöffnet. Schließen Sie die Brücke danach, um Kopplungsdaten zu entfernen.", installTitle: "Pratix Bridge zum Startbildschirm hinzufügen.", installHint: "Öffnen Sie diese Seite auf iPhone oder iPad in Safari, tippen Sie auf Teilen und dann auf Zum Home-Bildschirm. Nutzen Sie auf Android oder Chromium die Browser-Installationsoption." },
  es: { browserToBrowser: "Transferencia de navegador a navegador", ready: "Listo para emparejar", pairingExpired: "El emparejamiento expiró", needsAttention: "Requiere atención", createDescription: "Genera un código temporal y deja que el otro dispositivo se una con PIN o QR.", copy: "Copiar", copied: "Copiado", feedback: "Estado de transferencia", directMessages: "Tus mensajes directos aparecerán aquí.", item: "elemento", items: "elementos", sending: "Enviando", receiving: "Recibiendo", noStorage: "Sin almacenamiento de archivos", pairingWindow: "Ventana de emparejamiento de 10 minutos", worksAcrossNetworks: "Funciona entre redes", handoffTitle: "Creado para una entrega limpia.", handoffBody: "El PIN es solo para emparejar. Tus textos y archivos viajan directamente entre los dos navegadores.", adTitle: "Espacio reservado sin interrupciones", adBody: "El contenido patrocinado puede aparecer aquí sin cubrir controles ni comentarios de transferencia.", privacy: "Privacidad por diseño", privacyBody: "Mantén la página abierta durante la transferencia. Cierra el puente al terminar para eliminar los datos de emparejamiento.", installTitle: "Añade Pratix Bridge a tu pantalla de inicio.", installHint: "En iPhone o iPad, abre esta página en Safari, toca Compartir y selecciona Añadir a pantalla de inicio. En Android o Chromium usa la opción de instalar del navegador." },
  fr: { browserToBrowser: "Transfert de navigateur à navigateur", ready: "Prêt à associer", pairingExpired: "L'association a expiré", needsAttention: "Action requise", createDescription: "Générez un code limité dans le temps, puis laissez l'autre appareil rejoindre avec le PIN ou le QR code.", copy: "Copier", copied: "Copié", feedback: "État du transfert", directMessages: "Vos messages directs apparaîtront ici.", item: "élément", items: "éléments", sending: "Envoi", receiving: "Réception", noStorage: "Aucun stockage de fichiers", pairingWindow: "Fenêtre d'association de 10 minutes", worksAcrossNetworks: "Fonctionne entre réseaux", handoffTitle: "Conçu pour un transfert net.", handoffBody: "Le PIN sert seulement à l'association. Vos textes et fichiers voyagent directement entre les deux navigateurs.", adTitle: "Emplacement réservé et non intrusif", adBody: "Du contenu sponsorisé peut apparaître ici sans couvrir les commandes ou retours de transfert.", privacy: "Confidentialité par conception", privacyBody: "Gardez la page ouverte pendant le transfert. Fermez le pont à la fin pour supprimer les données d'association.", installTitle: "Ajoutez Pratix Bridge à l'écran d'accueil.", installHint: "Sur iPhone ou iPad, ouvrez cette page dans Safari, touchez Partager puis Ajouter à l'écran d'accueil. Sur Android ou Chromium, utilisez l'option d'installation du navigateur." },
  it: { browserToBrowser: "Trasferimento da browser a browser", ready: "Pronto per l'abbinamento", pairingExpired: "Abbinamento scaduto", needsAttention: "Richiede attenzione", createDescription: "Genera un codice a tempo, poi consenti all'altro dispositivo di unirsi con PIN o QR.", copy: "Copia", copied: "Copiato", feedback: "Stato del trasferimento", directMessages: "I messaggi diretti appariranno qui.", item: "elemento", items: "elementi", sending: "Invio", receiving: "Ricezione", noStorage: "Nessuna archiviazione file", pairingWindow: "Finestra di abbinamento di 10 minuti", worksAcrossNetworks: "Funziona tra reti", handoffTitle: "Pensato per un passaggio pulito.", handoffBody: "Il PIN serve solo all'abbinamento. Testi e file viaggiano direttamente tra i due browser.", adTitle: "Spazio riservato e non invasivo", adBody: "I contenuti sponsorizzati possono apparire qui senza coprire controlli o feedback del trasferimento.", privacy: "Privacy per progettazione", privacyBody: "Tieni la pagina aperta durante il trasferimento. Chiudi il ponte alla fine per rimuovere i dati di abbinamento.", installTitle: "Aggiungi Pratix Bridge alla schermata Home.", installHint: "Su iPhone o iPad apri la pagina in Safari, tocca Condividi e scegli Aggiungi a Home. Su Android o Chromium usa l'opzione di installazione del browser." },
  pt: { browserToBrowser: "Transferência de navegador para navegador", ready: "Pronto para emparelhar", pairingExpired: "O emparelhamento expirou", needsAttention: "Requer atenção", createDescription: "Gere um código temporário e deixe o outro dispositivo entrar com PIN ou QR.", copy: "Copiar", copied: "Copiado", feedback: "Estado da transferência", directMessages: "As suas mensagens diretas aparecerão aqui.", item: "item", items: "itens", sending: "A enviar", receiving: "A receber", noStorage: "Sem armazenamento de ficheiros", pairingWindow: "Janela de emparelhamento de 10 minutos", worksAcrossNetworks: "Funciona entre redes", handoffTitle: "Feito para uma passagem limpa.", handoffBody: "O PIN serve apenas para emparelhar. Os textos e ficheiros seguem diretamente entre os dois navegadores.", adTitle: "Espaço reservado e não intrusivo", adBody: "Conteúdo patrocinado pode aparecer aqui sem cobrir controlos ou respostas de transferência.", privacy: "Privacidade por design", privacyBody: "Mantenha a página aberta durante a transferência. Feche a ponte ao terminar para remover os dados de emparelhamento.", installTitle: "Adicione o Pratix Bridge ao ecrã inicial.", installHint: "No iPhone ou iPad abra esta página no Safari, toque em Partilhar e escolha Adicionar ao ecrã inicial. No Android ou Chromium use a opção de instalar do navegador." },
  nl: { browserToBrowser: "Browser-naar-browseroverdracht", ready: "Klaar om te koppelen", pairingExpired: "Koppeling verlopen", needsAttention: "Actie vereist", createDescription: "Maak een tijdelijke code en laat het andere apparaat toetreden met PIN of QR-code.", copy: "Kopiëren", copied: "Gekopieerd", feedback: "Overdrachtsstatus", directMessages: "Uw directe berichten verschijnen hier.", item: "item", items: "items", sending: "Verzenden", receiving: "Ontvangen", noStorage: "Geen bestandsopslag", pairingWindow: "Koppelvenster van 10 minuten", worksAcrossNetworks: "Werkt tussen netwerken", handoffTitle: "Gebouwd voor een nette overdracht.", handoffBody: "De PIN is alleen voor koppeling. Uw tekst en bestanden gaan rechtstreeks tussen de twee browsers.", adTitle: "Gereserveerde, niet-storende plaats", adBody: "Gesponsorde inhoud kan hier verschijnen zonder overdrachtsbediening of feedback te bedekken.", privacy: "Privacy door ontwerp", privacyBody: "Houd de pagina open tijdens een overdracht. Sluit de brug na afloop om koppelgegevens te verwijderen.", installTitle: "Voeg Pratix Bridge toe aan uw startscherm.", installHint: "Open deze pagina op iPhone of iPad in Safari, tik op Deel en kies Zet op beginscherm. Gebruik op Android of Chromium de installatieoptie van de browser." },
  ar: { browserToBrowser: "نقل من متصفح إلى متصفح", ready: "جاهز للاقتران", pairingExpired: "انتهت صلاحية الاقتران", needsAttention: "يتطلب اهتماماً", createDescription: "أنشئ رمزاً محدود الوقت، ثم دع الجهاز الآخر ينضم عبر PIN أو QR.", copy: "نسخ", copied: "تم النسخ", feedback: "حالة النقل", directMessages: "ستظهر رسائلك المباشرة هنا.", item: "عنصر", items: "عناصر", sending: "جارٍ الإرسال", receiving: "جارٍ الاستلام", noStorage: "لا تخزين للملفات", pairingWindow: "نافذة اقتران لمدة 10 دقائق", worksAcrossNetworks: "يعمل عبر الشبكات", handoffTitle: "مصمم لتسليم سلس.", handoffBody: "PIN مخصص للاقتران فقط. تنتقل النصوص والملفات مباشرة بين المتصفحين.", adTitle: "موضع مخصص غير معطّل", adBody: "يمكن أن يظهر محتوى برعاية هنا دون تغطية عناصر النقل أو ملاحظاته.", privacy: "خصوصية بالتصميم", privacyBody: "أبق الصفحة مفتوحة أثناء النقل. أغلق الجسر عند الانتهاء لإزالة بيانات الاقتران.", installTitle: "أضف جسر براتيكس إلى الشاشة الرئيسية.", installHint: "على iPhone أو iPad افتح هذه الصفحة في Safari ثم اضغط مشاركة واختر إضافة إلى الشاشة الرئيسية. على Android أو Chromium استخدم خيار تثبيت المتصفح." },
  ja: { browserToBrowser: "ブラウザ間転送", ready: "ペアリングの準備完了", pairingExpired: "ペアリングの期限切れ", needsAttention: "対応が必要です", createDescription: "時間制限付きコードを作成し、他の端末をPINまたはQRコードで接続します。", copy: "コピー", copied: "コピー済み", feedback: "転送フィードバック", directMessages: "ダイレクトメッセージはここに表示されます。", item: "件", items: "件", sending: "送信中", receiving: "受信中", noStorage: "ファイルを保存しません", pairingWindow: "10分間のペアリング", worksAcrossNetworks: "ネットワークをまたいで利用可能", handoffTitle: "すっきりした受け渡しのために。", handoffBody: "PINはペアリング専用です。選んだテキストとファイルは二つのブラウザ間を直接移動します。", adTitle: "控えめな予約枠", adBody: "スポンサーコンテンツは転送操作や通知を覆わずにここへ表示できます。", privacy: "プライバシーを考えた設計", privacyBody: "転送中はページを開いたままにしてください。終了後にブリッジを閉じるとペアリング情報が削除されます。", installTitle: "Pratix Bridgeをホーム画面に追加。", installHint: "iPhoneまたはiPadではSafariで開き、共有からホーム画面に追加を選びます。AndroidまたはChromiumではブラウザのインストール機能を使用してください。" },
  ko: { browserToBrowser: "브라우저 간 전송", ready: "페어링 준비 완료", pairingExpired: "페어링이 만료되었습니다", needsAttention: "주의가 필요합니다", createDescription: "시간 제한 코드를 만든 후 다른 기기에서 PIN 또는 QR로 참가하게 하세요.", copy: "복사", copied: "복사됨", feedback: "전송 피드백", directMessages: "직접 메시지가 여기에 표시됩니다.", item: "항목", items: "항목", sending: "보내는 중", receiving: "받는 중", noStorage: "파일 저장 없음", pairingWindow: "10분 페어링 창", worksAcrossNetworks: "네트워크 간 작동", handoffTitle: "깔끔한 전달을 위해 만들었습니다.", handoffBody: "PIN은 페어링용입니다. 선택한 텍스트와 파일은 두 브라우저 사이를 직접 이동합니다.", adTitle: "방해하지 않는 예약 영역", adBody: "스폰서 콘텐츠는 전송 제어 또는 피드백을 가리지 않고 여기에 표시될 수 있습니다.", privacy: "개인정보 중심 설계", privacyBody: "전송 중에는 페이지를 열어 두세요. 완료 후 브리지를 닫으면 페어링 메타데이터가 제거됩니다.", installTitle: "Pratix Bridge를 홈 화면에 추가하세요.", installHint: "iPhone 또는 iPad에서는 Safari로 열고 공유를 누른 다음 홈 화면에 추가를 선택하세요. Android 또는 Chromium에서는 브라우저 설치 옵션을 사용하세요." },
  zh: { browserToBrowser: "浏览器到浏览器传输", ready: "准备配对", pairingExpired: "配对已过期", needsAttention: "需要注意", createDescription: "生成限时码，然后让另一台设备通过 PIN 或二维码加入。", copy: "复制", copied: "已复制", feedback: "传输反馈", directMessages: "您的直接消息会显示在这里。", item: "个项目", items: "个项目", sending: "正在发送", receiving: "正在接收", noStorage: "不存储文件", pairingWindow: "10分钟配对窗口", worksAcrossNetworks: "可跨网络工作", handoffTitle: "为清爽交接而设计。", handoffBody: "PIN 仅用于配对。您选择的文本和文件会在两个浏览器之间直接传输。", adTitle: "预留且不打扰的位置", adBody: "赞助内容可显示在此处，而不会遮挡传输控制或任务反馈。", privacy: "隐私优先设计", privacyBody: "传输期间请保持页面打开。完成后关闭桥接以删除配对元数据。", installTitle: "将 Pratix Bridge 添加到主屏幕。", installHint: "在 iPhone 或 iPad 上，请用 Safari 打开此页，点击分享后选择添加到主屏幕。在 Android 或 Chromium 上，请使用浏览器安装选项。" },
} as const;

export type TranslationKey = BaseTranslationKey | keyof typeof additionalDictionaries.en;

export function translate(locale: Locale, key: TranslationKey) {
  if (key in additionalDictionaries.en) return additionalDictionaries[locale][key as keyof typeof additionalDictionaries.en];
  return dictionaries[locale][key as BaseTranslationKey] ?? dictionaries.en[key as BaseTranslationKey];
}
