import type { Locale } from "./i18n";

export type SeoGuideCopy = {
  eyebrow: string;
  title: string;
  intro: string;
  directHeading: string;
  directBody: string;
  stepsHeading: string;
  stepsBody: string;
  privacyHeading: string;
  privacyBody: string;
  keywordsLabel: string;
  keywords: string;
};

export const seoGuide: Record<Locale, SeoGuideCopy> = {
  en: { eyebrow: "SEO guide", title: "How direct P2P transfer works", intro: "Pratix Bridge is a browser-based P2P file transfer and text sharing tool for fast, private handoffs between two devices.", directHeading: "Send files without shared Wi-Fi", directBody: "Create a temporary six-digit PIN or QR code, pair a phone with a laptop or another browser, and send text and files through a WebRTC DataChannel. The transfer payload stays between the connected browsers instead of being uploaded to a file storage service.", stepsHeading: "A simple browser-to-browser workflow", stepsBody: "Create a bridge, share the PIN or scan the QR code, then select a message or file. Progress, queue state, download controls, and errors remain visible throughout the transfer. This makes secure file transfer without shared Wi-Fi practical for work, travel, and everyday device handoffs.", privacyHeading: "Private by design", privacyBody: "The pairing code is short-lived and used only to establish the connection. Keep both browsers open during an active transfer and close the bridge when you are finished.", keywordsLabel: "Search topics", keywords: "P2P file transfer · WebRTC file transfer · send files between phone and laptop · direct device-to-device file sharing" },
  tr: { eyebrow: "SEO rehberi", title: "Doğrudan P2P aktarımı nasıl çalışır?", intro: "Pratix Bridge, iki cihaz arasında hızlı ve özel aktarım için tarayıcı tabanlı P2P dosya ve metin paylaşım aracıdır.", directHeading: "Aynı Wi‑Fi olmadan dosya gönderin", directBody: "Süreli altı haneli PIN veya QR kodu oluşturun, telefonunuzu dizüstü bilgisayar ya da başka bir tarayıcıyla eşleştirin ve metin ile dosyaları WebRTC DataChannel üzerinden gönderin. Aktarım içeriği dosya depolama hizmetine yüklenmek yerine bağlı tarayıcılar arasında kalır.", stepsHeading: "Basit bir tarayıcıdan tarayıcıya akış", stepsBody: "Köprüyü oluşturun, PIN'i paylaşın veya QR kodu taratın, ardından mesaj ya da dosya seçin. İlerleme, kuyruk durumu, indirme kontrolleri ve hatalar aktarım boyunca görünür kalır. Bu sayede güvenli dosya transferi ve cihazlar arası doğrudan paylaşım iş, seyahat ve günlük kullanım için pratikleşir.", privacyHeading: "Gizlilik tasarımın parçası", privacyBody: "Eşleştirme kodu kısa ömürlüdür ve yalnızca bağlantı kurmak için kullanılır. Aktarım sırasında iki tarayıcıyı açık tutun, işiniz bittiğinde köprüyü kapatın.", keywordsLabel: "Arama konuları", keywords: "P2P dosya transferi · WebRTC dosya aktarımı · telefondan bilgisayara dosya gönderme · Wi‑Fi olmadan güvenli dosya paylaşımı" },
  de: { eyebrow: "SEO-Leitfaden", title: "So funktioniert direkter P2P-Transfer", intro: "Pratix Bridge ist ein browserbasiertes P2P-Tool für schnelle und private Text- und Dateiübergaben zwischen zwei Geräten.", directHeading: "Dateien ohne gemeinsames WLAN senden", directBody: "Erstellen Sie eine zeitlich begrenzte sechsstellige PIN oder einen QR-Code, koppeln Sie ein Smartphone mit einem Laptop oder Browser und senden Sie Texte und Dateien über einen WebRTC DataChannel. Die Nutzdaten bleiben zwischen den verbundenen Browsern.", stepsHeading: "Ein einfacher Browser-zu-Browser-Ablauf", stepsBody: "Brücke erstellen, PIN teilen oder QR-Code scannen und eine Nachricht oder Datei auswählen. Fortschritt, Warteschlange, Download und Fehler bleiben sichtbar. So wird sicherer Dateitransfer ohne gemeinsames WLAN für Arbeit, Reisen und Alltag unkompliziert.", privacyHeading: "Datenschutz als Designprinzip", privacyBody: "Der Kopplungscode ist kurzlebig und dient nur zum Verbindungsaufbau. Lassen Sie beide Browser während des Transfers geöffnet und schließen Sie die Brücke danach.", keywordsLabel: "Suchthemen", keywords: "P2P-Dateitransfer · WebRTC-Dateiübertragung · Dateien zwischen Smartphone und Laptop senden · direkter Geräteaustausch" },
  es: { eyebrow: "Guía SEO", title: "Cómo funciona la transferencia P2P directa", intro: "Pratix Bridge es una herramienta de transferencia P2P de archivos y texto desde el navegador para compartir de forma rápida y privada entre dos dispositivos.", directHeading: "Envía archivos sin compartir Wi‑Fi", directBody: "Crea un PIN temporal de seis dígitos o un código QR, conecta un teléfono con un portátil u otro navegador y envía texto y archivos mediante WebRTC DataChannel. Los datos de la transferencia permanecen entre los navegadores conectados.", stepsHeading: "Un flujo sencillo entre navegadores", stepsBody: "Crea el puente, comparte el PIN o escanea el QR y selecciona un mensaje o archivo. El progreso, la cola, la descarga y los errores siguen visibles. Así, la transferencia segura sin Wi‑Fi compartido resulta útil para trabajo, viajes y uso diario.", privacyHeading: "Privacidad desde el diseño", privacyBody: "El código de emparejamiento dura poco tiempo y solo establece la conexión. Mantén ambos navegadores abiertos durante la transferencia y cierra el puente al terminar.", keywordsLabel: "Temas de búsqueda", keywords: "transferencia de archivos P2P · transferencia de archivos WebRTC · enviar archivos del móvil al portátil · compartir archivos entre dispositivos" },
  fr: { eyebrow: "Guide SEO", title: "Comment fonctionne le transfert P2P direct", intro: "Pratix Bridge est un outil de transfert P2P de fichiers et de texte dans le navigateur, conçu pour des échanges rapides et privés entre deux appareils.", directHeading: "Envoyez des fichiers sans Wi‑Fi commun", directBody: "Créez un PIN temporaire à six chiffres ou un QR code, reliez un téléphone à un ordinateur ou à un autre navigateur, puis envoyez du texte et des fichiers via WebRTC DataChannel. Les données restent entre les navigateurs connectés.", stepsHeading: "Un parcours simple de navigateur à navigateur", stepsBody: "Créez le pont, partagez le PIN ou scannez le QR code, puis choisissez un message ou un fichier. La progression, la file, le téléchargement et les erreurs restent visibles. Le partage de fichiers sécurisé sans Wi‑Fi commun devient ainsi pratique au travail, en voyage et au quotidien.", privacyHeading: "La confidentialité par conception", privacyBody: "Le code d'association est éphémère et sert uniquement à établir la connexion. Gardez les deux navigateurs ouverts pendant le transfert et fermez le pont ensuite.", keywordsLabel: "Sujets de recherche", keywords: "transfert de fichiers P2P · transfert de fichiers WebRTC · envoyer des fichiers du téléphone à l'ordinateur · partage direct entre appareils" },
  it: { eyebrow: "Guida SEO", title: "Come funziona il trasferimento P2P diretto", intro: "Pratix Bridge è uno strumento nel browser per trasferire file e testo in modo rapido e privato tra due dispositivi.", directHeading: "Invia file senza Wi‑Fi condiviso", directBody: "Crea un PIN temporaneo di sei cifre o un codice QR, collega il telefono a un portatile o a un altro browser e invia testo e file tramite WebRTC DataChannel. I dati restano tra i browser collegati.", stepsHeading: "Un flusso semplice tra browser", stepsBody: "Crea il ponte, condividi il PIN o scansiona il QR, quindi scegli un messaggio o un file. Progresso, coda, download ed errori restano visibili. Il trasferimento sicuro senza Wi‑Fi condiviso diventa utile al lavoro, in viaggio e ogni giorno.", privacyHeading: "Privacy progettata", privacyBody: "Il codice di abbinamento è temporaneo e serve solo a creare la connessione. Tieni aperti entrambi i browser durante il trasferimento e chiudi il ponte alla fine.", keywordsLabel: "Temi di ricerca", keywords: "trasferimento file P2P · trasferimento file WebRTC · inviare file dal telefono al laptop · condivisione diretta tra dispositivi" },
  pt: { eyebrow: "Guia SEO", title: "Como funciona a transferência P2P direta", intro: "O Pratix Bridge é uma ferramenta no navegador para transferir texto e ficheiros de forma rápida e privada entre dois dispositivos.", directHeading: "Envie ficheiros sem Wi‑Fi partilhado", directBody: "Crie um PIN temporário de seis dígitos ou um código QR, ligue um telemóvel a um portátil ou a outro navegador e envie texto e ficheiros através de WebRTC DataChannel. Os dados permanecem entre os navegadores ligados.", stepsHeading: "Um fluxo simples entre navegadores", stepsBody: "Crie a ponte, partilhe o PIN ou leia o QR e escolha uma mensagem ou ficheiro. O progresso, a fila, a transferência e os erros ficam visíveis. A transferência segura sem Wi‑Fi partilhado torna-se prática no trabalho, em viagem e no dia a dia.", privacyHeading: "Privacidade por design", privacyBody: "O código de emparelhamento é temporário e serve apenas para estabelecer a ligação. Mantenha os dois navegadores abertos durante a transferência e feche a ponte no fim.", keywordsLabel: "Temas de pesquisa", keywords: "transferência de ficheiros P2P · transferência de ficheiros WebRTC · enviar ficheiros do telemóvel para o portátil · partilha direta entre dispositivos" },
  nl: { eyebrow: "SEO-gids", title: "Hoe directe P2P-overdracht werkt", intro: "Pratix Bridge is een browserhulpmiddel voor snelle, privé tekst- en bestandsoverdracht tussen twee apparaten.", directHeading: "Verstuur bestanden zonder gedeelde wifi", directBody: "Maak een tijdelijke zescijferige PIN of QR-code, verbind een telefoon met een laptop of andere browser en verstuur tekst en bestanden via WebRTC DataChannel. De overdrachtsgegevens blijven tussen de verbonden browsers.", stepsHeading: "Een eenvoudige browser-naar-browserflow", stepsBody: "Maak de brug, deel de PIN of scan de QR-code en kies een bericht of bestand. Voortgang, wachtrij, downloads en fouten blijven zichtbaar. Zo wordt veilige bestandsoverdracht zonder gedeelde wifi praktisch voor werk, reizen en dagelijks gebruik.", privacyHeading: "Privacy door ontwerp", privacyBody: "De koppelcode is tijdelijk en wordt alleen gebruikt om de verbinding te maken. Houd beide browsers open tijdens de overdracht en sluit de brug daarna.", keywordsLabel: "Zoekonderwerpen", keywords: "P2P-bestandsoverdracht · WebRTC-bestandsoverdracht · bestanden tussen telefoon en laptop sturen · direct bestanden delen tussen apparaten" },
  ar: { eyebrow: "دليل تحسين الظهور", title: "كيف يعمل النقل المباشر عبر P2P", intro: "Pratix Bridge أداة تعمل في المتصفح لنقل النصوص والملفات بسرعة وخصوصية بين جهازين.", directHeading: "أرسل الملفات دون شبكة واي فاي مشتركة", directBody: "أنشئ رمز PIN مؤقتاً من ستة أرقام أو رمز QR، وصِل الهاتف بجهاز محمول أو متصفح آخر، ثم أرسل النصوص والملفات عبر WebRTC DataChannel. تبقى بيانات النقل بين المتصفحين المتصلين.", stepsHeading: "خطوات بسيطة بين المتصفحات", stepsBody: "أنشئ الجسر، شارك رمز PIN أو امسح QR، ثم اختر رسالة أو ملفاً. يظل التقدم وقائمة الانتظار والتنزيل والأخطاء واضحة. لذلك يصبح نقل الملفات الآمن دون واي فاي مشترك عملياً للعمل والسفر والاستخدام اليومي.", privacyHeading: "الخصوصية جزء من التصميم", privacyBody: "رمز الاقتران مؤقت ويُستخدم لإنشاء الاتصال فقط. أبقِ المتصفحين مفتوحين أثناء النقل وأغلق الجسر عند الانتهاء.", keywordsLabel: "موضوعات البحث", keywords: "نقل ملفات P2P · نقل ملفات WebRTC · إرسال الملفات من الهاتف إلى الكمبيوتر المحمول · مشاركة مباشرة بين الأجهزة" },
  ja: { eyebrow: "SEOガイド", title: "直接P2P転送の仕組み", intro: "Pratix Bridgeは、2台の端末間でテキストとファイルをすばやく安全に受け渡せるブラウザツールです。", directHeading: "同じWi‑Fiなしでファイルを送る", directBody: "6桁の一時PINまたはQRコードを作成し、スマートフォンとノートパソコンなどを接続して、WebRTC DataChannelでテキストやファイルを送信します。転送データは接続されたブラウザ間に保たれます。", stepsHeading: "シンプルなブラウザ間フロー", stepsBody: "ブリッジを作成し、PINを共有またはQRをスキャンして、メッセージやファイルを選びます。進捗、キュー、ダウンロード、エラーが常に表示されるため、共有Wi‑Fiなしの安全なファイル転送を仕事や旅行でも使えます。", privacyHeading: "プライバシーを考えた設計", privacyBody: "ペアリングコードは短時間だけ有効で、接続の確立にのみ使われます。転送中は両方のブラウザを開いたままにし、終了後にブリッジを閉じてください。", keywordsLabel: "検索テーマ", keywords: "P2Pファイル転送 · WebRTCファイル転送 · スマホからノートパソコンへファイル送信 · 端末間の直接ファイル共有" },
  ko: { eyebrow: "SEO 가이드", title: "직접 P2P 전송 작동 방식", intro: "Pratix Bridge는 두 기기 사이에서 텍스트와 파일을 빠르고 비공개로 전달하는 브라우저 도구입니다.", directHeading: "같은 Wi‑Fi 없이 파일 보내기", directBody: "6자리 임시 PIN 또는 QR 코드를 만들고 휴대폰과 노트북 또는 다른 브라우저를 연결한 뒤 WebRTC DataChannel로 텍스트와 파일을 전송합니다. 전송 데이터는 연결된 브라우저 사이에만 머뭅니다.", stepsHeading: "간단한 브라우저 간 흐름", stepsBody: "브리지를 만들고 PIN을 공유하거나 QR을 스캔한 다음 메시지나 파일을 선택하세요. 진행률, 대기열, 다운로드와 오류가 계속 표시됩니다. 공유 Wi‑Fi 없는 안전한 파일 전송을 업무, 여행, 일상에서 활용할 수 있습니다.", privacyHeading: "개인정보 중심 설계", privacyBody: "페어링 코드는 짧은 시간만 유효하며 연결 설정에만 사용됩니다. 전송 중에는 두 브라우저를 열어 두고 완료 후 브리지를 닫으세요.", keywordsLabel: "검색 주제", keywords: "P2P 파일 전송 · WebRTC 파일 전송 · 휴대폰에서 노트북으로 파일 보내기 · 기기 간 직접 파일 공유" },
  zh: { eyebrow: "SEO 指南", title: "直接 P2P 传输如何工作", intro: "Pratix Bridge 是一款浏览器工具，可在两台设备之间快速、私密地传输文本和文件。", directHeading: "无需共享 Wi‑Fi 即可发送文件", directBody: "创建一个限时六位 PIN 或二维码，将手机与笔记本电脑或另一个浏览器配对，然后通过 WebRTC DataChannel 发送文本和文件。传输内容只保留在已连接的浏览器之间。", stepsHeading: "简单的浏览器间流程", stepsBody: "创建桥接，分享 PIN 或扫描二维码，再选择消息或文件。进度、队列、下载和错误始终清晰可见。无共享 Wi‑Fi 的安全文件传输因此适用于工作、旅行和日常设备交接。", privacyHeading: "隐私优先设计", privacyBody: "配对码短期有效，仅用于建立连接。传输期间请保持两个浏览器打开，完成后关闭桥接。", keywordsLabel: "搜索主题", keywords: "P2P 文件传输 · WebRTC 文件传输 · 手机与笔记本电脑互传文件 · 设备间直接文件共享" },
};
